### ISSUE TITLE
Latest FPGA with Latest Application doesn't work with multiple PPS

### ISSUE THREAD

**Issue by rfunderburk** [NetTimeLogic/UniversalPpsAnalyzer#2]
When using the latest FPGA image, with the latest application, multiple PPS inputs are just overlapping each other. Only if one of the PPS inputs is disconnected are there multiple PPS lines shown but, of course, one of them is always zero.

**Comment by rfunderburk** [comment]
Note that this only applies to the Application binary as contained in this repository. If the binary is used that is supplied with the FPGA image then the output is as expected.

**Comment by sven-marc-meier** [comment]
The executable was not updated. Dod this right now
